#!/bin/sh

sed -i '/include/a #include "Parserbase.h"' Scanner.ih;
sed -i '/insert preincludes/a #include "ast.h"' Parserbase.h;
sed -i '/insert preincludes/a #include "symtab.h"' Parserbase.h;
sed -i '/include "Parser.h"/a #include "ast.cc"' Parser.ih;
sed -i '/include "Parser.h"/a #include "symtab.cc"' Parser.ih;

sed -i '\|STYPE__     d_val__;| d
' Parserbase.h

sed -i '\|typedef Meta__::SType STYPE__;| a \\tpublic: static STYPE__  d_val__;\nstatic int line;
' Parserbase.h


sed -i '\|void Parser::print__()| i Meta__::SType ParserBase::d_val__;\nint ParserBase::line=1;
' parse.cc
